services:
  # 1. PostgreSQL Datenbank
  db:
    image: postgres:16-alpine
    container_name: django_db
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: my_django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis (für Caching & Django Channels / Websockets)
  redis:
    image: redis:7-alpine
    container_name: django_redis
    ports:
      - "6379:6379"

  # 3. Webserver (Django mit Daphne für HTTP + Websockets)
  web:
    build: .
    container_name: django_web
    # Daphne startet die ASGI-App, damit Websockets out-of-the-box funktionieren
    command: daphne -b 0.0.0.0 -p 8000 izz.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - TZ=Europe/Berlin
      - DB_HOST=db
      - DB_NAME=my_django_db
      - DB_USER=django_user
      - DB_PASSWORD=secure_password
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  # 4. Celery Worker (Führt die Aufgaben aus)
  celery:
    build: .
    container_name: django_celery
    command: celery -A izz worker --loglevel=info --uid=nobody
    volumes:
      - .:/code
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=db
      - DB_NAME=my_django_db
      - DB_USER=django_user
      - DB_PASSWORD=secure_password
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

volumes:
  postgres_data: