# Generated by Django 6.0.6 on 2026-06-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gleis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gleis_nummer', models.CharField(max_length=10, unique=True, verbose_name='Gleisnummer')),
                ('sensor_belegt', models.BooleanField(default=False, verbose_name='Sensor: Gleis belegt?')),
                ('laenge_meter', models.PositiveIntegerField(default=300, verbose_name='Gleislänge in Metern')),
            ],
        ),
        migrations.CreateModel(
            name='Zug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zug_nummer', models.CharField(max_length=20, unique=True, verbose_name='Zug-ID (z.B. ICE 721)')),
                ('status', models.CharField(choices=[('WARTET', 'Wartet am Einfahrtssignal'), ('FAHRT', 'Fährt in den Bahnhof ein'), ('GEPARKT', 'Steht am Gleis'), ('ABGEFAHREN', 'Hat den Bahnhof verlassen')], default='WARTET', max_length=20)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StellwerkAnfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfrage_zeit', models.DateTimeField(auto_now_add=True)),
                ('ergebnis', models.CharField(choices=[('OFFEN', 'In Bearbeitung / Zug wartet'), ('GENEHMIGT', 'Einfahrt erlaubt'), ('ABGEWIESEN', 'Kein Gleis frei / Bitte warten')], default='OFFEN', max_length=20)),
                ('zugewiesenes_gleis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.gleis')),
                ('zug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.zug')),
            ],
        ),
        migrations.CreateModel(
            name='Fahrstrasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ist_aktiv', models.BooleanField(default=True, verbose_name='Fahrstraße freigeschaltet (Reserviert)')),
                ('freigeschaltet_um', models.DateTimeField(auto_now_add=True)),
                ('gleis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservierungen', to='web.gleis')),
                ('zug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservierungen', to='web.zug')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ist_aktiv', True)), fields=('gleis',), name='einzigartige_aktive_gleis_reservierung')],
            },
        ),
    ]
