# Generated by Django 6.0.6 on 2026-06-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fahrstrasse',
            options={'verbose_name': 'Fahrstraße', 'verbose_name_plural': 'Fahstraßen'},
        ),
        migrations.AlterModelOptions(
            name='gleis',
            options={'verbose_name': 'Gleis', 'verbose_name_plural': 'Gleise'},
        ),
        migrations.AlterModelOptions(
            name='stellwerkanfrage',
            options={'verbose_name': 'Stellwerkanfrage', 'verbose_name_plural': 'Stellwerkanfragen'},
        ),
        migrations.AlterModelOptions(
            name='zug',
            options={'verbose_name': 'Zug', 'verbose_name_plural': 'Züge'},
        ),
    ]
