# Generated by Django 6.0.6 on 2026-07-01 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_fahrstrasse_options_alter_gleis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fahrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrt_beginn', models.DateTimeField(blank=True, null=True, verbose_name='Fahrtbeginn')),
                ('fahrt_ende', models.DateTimeField(blank=True, null=True, verbose_name='Fahrtende')),
                ('lokfuehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.zug')),
            ],
            options={
                'verbose_name': 'Fahrt',
                'verbose_name_plural': 'Fahrten',
            },
        ),
        migrations.AddField(
            model_name='zug',
            name='lokfuehrer',
            field=models.ManyToManyField(blank=True, related_name='zuege', through='web.Fahrt', to=settings.AUTH_USER_MODEL, verbose_name='Lokführer'),
        ),
    ]
