# Generated by Django 6.0.6 on 2026-07-01 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_fahrt_zug_lokfuehrer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fahrt',
            constraint=models.UniqueConstraint(condition=models.Q(('fahrt_ende__isnull', True)), fields=('lokfuehrer',), name='ein_lokfuehrer_pro_aktive_fahrt'),
        ),
        migrations.AddConstraint(
            model_name='fahrt',
            constraint=models.UniqueConstraint(condition=models.Q(('fahrt_ende__isnull', True)), fields=('zug',), name='ein_zug_pro_aktive_fahrt'),
        ),
    ]
