# Generated by Django 6.0.6 on 2026-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_fahrt_ein_lokfuehrer_pro_aktive_fahrt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stellwerkanfrage',
            name='ergebnis',
            field=models.CharField(choices=[('OFFEN', 'In Bearbeitung / Zug wartet'), ('GENEHMIGT', 'Einfahrt erlaubt'), ('ABGEWIESEN', 'Kein Gleis frei / Bitte warten'), ('BEENDEN', 'Abgeschlossen')], default='OFFEN', max_length=20),
        ),
    ]
