name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Code aus dem GitHub-Repository auschecken
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Die Docker-Container exakt nach deiner docker-compose.yml bauen und starten
    - name: Build and start containers
      run: docker compose up -d --build

    # 3. Dem PostgreSQL-Container kurz Zeit geben, um hochzufahren und Verbindungen zu erlauben
    - name: Wait for PostgreSQL to be ready
      run: |
        echo "Warte auf Datenbank..."
        sleep 10
        docker compose ps

    # 4. Datenbank-Migrationen im 'web'-Container ausführen
    - name: Run Migrations
      run: docker compose exec -T web python manage.py migrate

    # 5. Fixtures laden
    - name: Load Fixtures
      run: docker compose exec web python manage.py loaddata default_data

    # 5. Django System-Checks laufen lassen (prüft Einstellungen und Models)
    - name: Run Django System Checks
      run: docker compose exec -T web python manage.py check

    # 6. Django-Tests ausführen (falls vorhanden)
    - name: Run Tests
      run: docker compose exec -T web python manage.py test

    # 7. Container nach dem Durchlauf stoppen und aufräumen
    - name: Shut down containers
      if: always()
      run: docker compose down -v